accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register_view"),
    path("login/", views.LoginView.as_view(), name="login_view"),
]

audio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home_view"),
    path('meeting/', views.MeetingView.as_view(), name="meeting_view"),
    path('meeting-verification/<slug:SLUG>/', views.MeetingVerification.as_view(), name="meeting_verification"),
    path('meeting-verification/complete/<slug:SLUG>/<str:MEETING_ID>/', views.MeetingVerification.as_view(), name="meeting_verification"),
    path('meeting/<slug:SLUG>/', views.InsideMeetingView.as_view(), name="inside_meeting_view"),
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Meeting(models.Model):
    user = models.OneToOneField(User, related_name="user", on_delete=models.CASCADE)
    meeting_title = models.CharField(max_length=255)
    qr_image = models.ImageField(blank=True, null=True, upload_to='QRCode')
    meeting_id = models.CharField(max_length=255)
    attendee = models.ManyToManyField(User, related_name="attendee")
    slug = models.SlugField()
    active = models.BooleanField(default=True)
    timestamp = models.DateField(auto_now_add=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.

class RegisterView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "accounts/register.html")

    def post(self, request, *args, **kwargs):
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        password = request.POST.get("password")
        User.objects.create_user(username=email, password=password, email=email, first_name=first_name, last_name=last_name)
        return redirect("accounts:login_view")


class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "accounts/login.html")

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("home:meeting_view")
        else:
            return redirect("accounts:login_view")

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Meeting
from django.http import HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
import qrcode
import qrcode.image.svg
import time
from django.utils.text import slugify
from .otp_generator import meetingID

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, "home/index.html")


class MeetingView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        all_meeting = Meeting.objects.all().order_by("-timestamp")

        context = {
            "all_meeting": all_meeting
        }
        return render(request, "home/meeting.html", context)

    def post(self, request, *args, **kwargs):
        if Meeting.objects.filter(user=request.user).exists():
            return HttpResponse("<h3>You already have an active meeting</h3>")
        else:
            meeting_title = request.POST.get("meeting_title")
            meeting_slug = slugify(meeting_title)
            meeting_id = meetingID()

            #QR code
            # Data to encode
            data = f"https://web-production-7428.up.railway.app/meeting-verification/complete/{meeting_slug}/{meeting_id}/"
            # Creating an instance of QRCode class
            qr = qrcode.QRCode(version = 1,
                box_size = 10,
                border = 5)
            #Adding data to the instance 'qr'
            qr.add_data(data)
            
            qr.make(fit = True)
            img = qr.make_image(fill_color = 'red',
                                back_color = 'white')
            img_name = f'/QRCode/{meeting_slug}'+str(time.time())+'.png'
            img.save(settings.MEDIA_ROOT + img_name)

            meet = Meeting.objects.create(
                user=request.user, meeting_title=meeting_title, qr_image=img_name, slug=meeting_slug, meeting_id=meeting_id
            )
            return redirect("home:inside_meeting_view", SLUG=meet.slug)


class MeetingVerification(LoginRequiredMixin, View):
    def get(self, request, SLUG, *args, **kwargs):
        try:
            current_meeting = Meeting.objects.get(slug=SLUG)
        except:
            return HttpResponse("<h3>Meeting no longer exist</h3>")
        attendee = request.user
        verification = False
        for i in current_meeting.attendee.all():
            if i == attendee:
                verification = True
                break
        if verification:
            return redirect("home:inside_meeting_view", SLUG=current_meeting.slug)
        else:
            return HttpResponse("<h3>Scan the QR Code on the meeting ground to gain access</h3>")


class MeetingVerificationComplete(LoginRequiredMixin, View):
    def get(self, request, SLUG, MEETING_ID, *args, **kwargs):
        try:
            current_meeting = Meeting.objects.get(slug=SLUG, meeting_id=MEETING_ID)
        except:
            return HttpResponse("<h3>Meeting no longer exist</h3>")
        current_meeting.attendee.add(request.user)
        return redirect("home:inside_meeting_view", SLUG=current_meeting.slug)


class InsideMeetingView(LoginRequiredMixin, View):
    def get(self, request, SLUG, *args, **kwargs):
        try:
            current_meeting = Meeting.objects.get(slug=SLUG)
            print(current_meeting.qr_image.url)
        except:
            return HttpResponse("<h3>Meeting no longer exist</h3>")


        context = {
            "current_meeting": current_meeting,
        }
        return render(request, "home/inside-meeting.html", context)

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>

    <div style="height: 100vh; width:100%;" class="d-flex justify-content-center align-items-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputEmail4">Email</label>
                  <input type="email" class="form-control" placeholder="Enter email" name="email" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputEmail4">Password</label>
                  <input type="password" class="form-control" placeholder="Enter password" name="password" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                  <button type="submit" class="submit-btn">Login</button>
                </div>
            </div>
        </form>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>

    <div style="height: 100vh; width:100%;" class="d-flex justify-content-center align-items-center">
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="inputEmail4">First Name</label>
                  <input type="text" class="form-control" placeholder="Enter First Name" name="first_name" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Last Name</label>
                    <input type="text" class="form-control" placeholder="Enter Last Name" name="last_name" required>
                  </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputEmail4">Email</label>
                  <input type="email" class="form-control" placeholder="Enter email" name="email" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputEmail4">Password</label>
                  <input type="password" class="form-control" placeholder="Enter password" name="password" required>
                  <div style="margin: 0px;">
                    <ul style="margin: 0px;">
                        <li>musrr</li>
                        <li>dvdfsf</li>
                    </ul>
                  </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                  <button type="submit" class="submit-btn">Register</button>
                </div>
            </div>
        </form>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>

    <div style="height: 100vh; width:100%;" class="d-flex justify-content-center align-items-center">
        <div>
            <div class="row">
                <a href="{% url 'accounts:register_view' %}" class="btn btn-transparent" style="margin-right: 5px;">Register</a> <a href="{% url 'accounts:login_view' %}" class="btn btn-primary">Login</a>
            </div>
        </div>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/inside-meeting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    
    <!-- <div style="height: 100vh;">
        <img src="{% static 'qr_images/MyQRCode1.png' %}" alt="" style="width: 100%; height:100%;">
    </div> -->

    

    {% if current_meeting.user != request.user %}
    <div style="height: 100vh; width:100%;" class="d-flex justify-content-center align-items-center">
        <img src="{% static 'images/off-speaking-removebg-preview.png' %}" alt="" id="stop" height="250" width="200">
        <img src="{% static 'images/on-speaking-removebg-preview.png' %}" alt="" id="speak" height="250" width="200">
    </div>
    {% else %}
    <div style="height: 100vh; width:100%;" class="d-flex justify-content-center align-items-center">
        <div>
            <img data-toggle="modal" data-target="#endMeeting" src="{% static 'images/end-meeting-removebg-preview.png' %}" alt="" id="stop" height="250" width="200">
        </div>
        <div>
            <a class="btn btn-transparent" data-toggle="modal" data-target="#viewQR">View QR Code</a>
        </div>
    </div>

    <audio id="player"></audio>
    {% endif %}

    <!-- viewQR Modal -->
    <div class="modal fade" id="viewQR" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Meeting QR Code</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <img class="mx-auto d-block" src="{{ current_meeting.qr_image.url }}" alt="">
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>


    <!-- endMeeting Modal -->
    <div class="modal fade" id="endMeeting" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">End Meeting</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <p class="text-center">Do you wish to end the meeting?</p>
                    </div>
                </div>
                <div>
                    <a class="end-btn" href="" style="color: white;">End</a>
                </div>
            </div>
        </div>
        </div>
    </div>



    <script>
        const player = document.getElementById('player');
        const stopButton = document.getElementById('stop');
        const speakButton = document.getElementById('speak');

        const handleSuccess = function (stream) {
            if (window.URL) {
                player.srcObject = stream;
            } else {
                player.src = stream;
            }

            stopButton.addEventListener('click', function(){
                player.pause()
                document.getElementById('stop').style.display = "none"
                document.getElementById('speak').style.display = "block"
            });

            speakButton.addEventListener('click', function(){
                player.play()
                document.getElementById('speak').style.display = "none"
                document.getElementById('stop').style.display = "block"
            });
        };

        navigator.mediaDevices
            .getUserMedia({audio: true, video: false})
            .then(handleSuccess);
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

home/templates/home/meeting-verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

home/templates/home/meeting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>

    <div style="height: 100vh; width:100%;" class="d-flex justify-content-center align-items-center">
        <div>
            <div class="row">
                <a class="btn btn-transparent" style="margin-right: 5px;" data-toggle="modal" data-target="#createMeeting">Create a Meeting</a> <a class="btn btn-transparent" data-toggle="modal" data-target="#joinMeeting">Join a Meeting</a>
            </div>
        </div>
    </div>

    <!-- createMeeting Modal -->
    <div class="modal fade" id="createMeeting" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create Meeting</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                          <label for="inputEmail4">Meeting Title</label>
                          <input type="text" class="form-control" placeholder="Meeting Title" name="meeting_title" required> 
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                          <button type="submit" class="submit-btn">Create</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>


    <!-- joinMeeting Modal -->
    <div class="modal fade" id="joinMeeting" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Join Meeting</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="search_meeting">
                    <input type="text" class="form-control" placeholder="Search Meeting" name="q">
                </div>
                {% if all_meeting %}
                <div>
                    {% for items in all_meeting %}
                    <a class="meetings" href="{% url 'home:meeting_verification' SLUG=items.slug %}">{{ items.meeting_title }}</a>
                    {% endfor %}
                </div>
                {% else %}
                <div>
                    <p>No meeting available at the moment</p>
                </div>
                {% endif %}
            </div>
        </div>
        </div>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>